spring:
  datasource:
    url: jdbc:mysql://mutso-db.ccbqj1f1cmqf.ap-northeast-2.rds.amazonaws.com:3306/music
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: mutso
    password: likelion12
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect
    defer-datasource-initialization: true
    database: h2
  sql:
    init:
      mode: always

  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB
  mvc:
    # /static/ ?? ???? ??? ?? ?? ?? ??
    static-path-pattern: /static/**
  web:
    resources:
      # ?? ?? ?? ??
      static-locations: file:back/,classpath:/static


jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve




