spring:
  datasource:
    url: jdbc:mysql://localhost:8080/db?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: password
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    database-platform:
    database: h2
  mvc:
    static-path-pattern: /static/**
  web:
    resources:
      static-locations: file:images/,classpath:/static
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

jwt:
  secret: aaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesoioegwaaaabbbsdifqbvaesasdfqve



